import Head from 'next/head';
import type { AppProps } from 'next/app';
import { GlobalStyle } from '@/styles/global';
import { AuthProvider } from '@/contexts/AuthContext';
import { CookiesProvider } from 'react-cookie';
import { TransactionsProvider } from '@/contexts/TransactionsContext';
import ReactModal from 'react-modal';

import 'react-toastify/dist/ReactToastify.css';

ReactModal.setAppElement('#__next');

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <CookiesProvider>
        <AuthProvider>
          <TransactionsProvider>
            <Head>
              <title>Afiliados</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
          </TransactionsProvider>
        </AuthProvider>
      </CookiesProvider>
    </>
  );
}
